/**
 * OpenAPI document loader.
 * Reads dist/openapi.json generated by `npm run generate:openapi`.
 */
import * as fs from 'fs';
import * as path from 'path';

let cached: Record<string, unknown> | null = null;

export function getOpenApiDoc(): Record<string, unknown> {
  if (cached) return cached;

  const docPath = path.join(process.cwd(), 'dist', 'openapi.json');
  if (!fs.existsSync(docPath)) {
    throw new Error(`openapi.json not found at ${docPath}. Run: npm run generate:openapi`);
  }
  cached = JSON.parse(fs.readFileSync(docPath, 'utf8')) as Record<string, unknown>;
  return cached;
}

// Named export for dynamic import in app.ts
export const openApiDoc: Record<string, unknown> = (() => {
  try {
    return getOpenApiDoc();
  } catch {
    return {};
  }
})();
